// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/metabition/genny

package math

// Complex128Max gets the maximum number from the
// two specified.
func Complex128Max(a, b complex128) complex128 {
	if a > b {
		return a
	}
	return b
}

// Complex64Max gets the maximum number from the
// two specified.
func Complex64Max(a, b complex64) complex64 {
	if a > b {
		return a
	}
	return b
}

// Float32Max gets the maximum number from the
// two specified.
func Float32Max(a, b float32) float32 {
	if a > b {
		return a
	}
	return b
}

// Float64Max gets the maximum number from the
// two specified.
func Float64Max(a, b float64) float64 {
	if a > b {
		return a
	}
	return b
}

// IntMax gets the maximum number from the
// two specified.
func IntMax(a, b int) int {
	if a > b {
		return a
	}
	return b
}

// Int16Max gets the maximum number from the
// two specified.
func Int16Max(a, b int16) int16 {
	if a > b {
		return a
	}
	return b
}

// Int32Max gets the maximum number from the
// two specified.
func Int32Max(a, b int32) int32 {
	if a > b {
		return a
	}
	return b
}

// Int64Max gets the maximum number from the
// two specified.
func Int64Max(a, b int64) int64 {
	if a > b {
		return a
	}
	return b
}

// Int8Max gets the maximum number from the
// two specified.
func Int8Max(a, b int8) int8 {
	if a > b {
		return a
	}
	return b
}

// UintMax gets the maximum number from the
// two specified.
func UintMax(a, b uint) uint {
	if a > b {
		return a
	}
	return b
}

// Uint16Max gets the maximum number from the
// two specified.
func Uint16Max(a, b uint16) uint16 {
	if a > b {
		return a
	}
	return b
}

// Uint32Max gets the maximum number from the
// two specified.
func Uint32Max(a, b uint32) uint32 {
	if a > b {
		return a
	}
	return b
}

// Uint64Max gets the maximum number from the
// two specified.
func Uint64Max(a, b uint64) uint64 {
	if a > b {
		return a
	}
	return b
}

// Uint8Max gets the maximum number from the
// two specified.
func Uint8Max(a, b uint8) uint8 {
	if a > b {
		return a
	}
	return b
}
