// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package buildtags

import (
	"fmt"
)

// +build x,y z

func intPrint(t int) {
	fmt.Println(t)
}
