// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package bugreports

type ObjInt struct {
	v int
}

func NewInts() (*ObjInt, []ObjInt) {
	n := new(ObjInt)
	m := make([]ObjInt, 0)
	return n, m
}
