// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package renamed

import (
	"fmt"

	testpkg "github.com/moriyoshi/genny/parse/test/renamed/subpkg"
)

func someFuncint() {
	var t int
	fmt.Println(t)
	fmt.Println(testpkg.Bar)
}
