// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package queue

// int64Queue is a queue of int64s.
type int64Queue struct {
	items []int64
}

func NewInt64Queue() *int64Queue {
	return &int64Queue{items: make([]int64, 0)}
}
func (q *int64Queue) Push(item int64) {
	q.items = append(q.items, item)
}
func (q *int64Queue) Pop() int64 {
	item := q.items[0]
	q.items = q.items[1:]
	return item
}
