// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package extrapackages

import "github.com/cheekybits/genny/parse/test/extrapackages/extrapkg"

func ExtrapkgMyTypeSayHello(a extrapkg.MyType) extrapkg.MyType {
	return a
}
